### ISSUE TITLE
Issue using Dask cluster with tiledbvcf

### ISSUE THREAD

**Issue by bruno-ariano** [TileDB-Inc/TileDB-VCF#764]
Hello, I am having an issue running map_dask on a tiledb-vcf. The version of tiledb-vcf that I am using is the most recent one, the 0.34.2. This issue appear only after I create a Dask cluster on my HPC and I read and apply the map_dask function on a dataset read from S3. For example when I read the same file on a local folder I don't have any problem. Below is the code I have used when running into the issue:

First I modify the default configuration for reading in S3
```
import pathlib
import tiledb
import tiledbvcf
cfg = tiledb.Config()
cfg["vfs.s3.aws_access_key_id"] = "xxx"
cfg["vfs.s3.aws_secret_access_key"] = "xxx"
cfg["vfs.s3.endpoint_override"] = "xxx"
cfg["vfs.s3.use_virtual_addressing"] = "false"
cfg["vfs.s3.scheme"] = "https"
cfg["vfs.s3.region"] = ""
cfg["vfs.s3.verify_ssl"] = "false"
read_cfg = tiledbvcf.ReadConfig(tiledb_config=cfg)
```

Then I create a Dask cluster
```
from dask_jobqueue import SLURMCluster as Cluster
from dask.distributed import Client
cluster = Cluster(cores = 1, memory="8 GB",processes=1,interface='ib0')
cluster.scale(3)
client = Client(cluster)
```

Finally I read the dataset and try to use the function map_dask on it to filter for some value
```
uri="s3://tiledb/ukb_vcf_data"
ds = tiledbvcf.Dataset(uri, mode = "r", cfg = read_cfg)
dask_df = ds.map_dask( lambda df: df[df.fmt_ES<2] ,
                        attrs = ["sample_name", "pos_start", "pos_end", "fmt_ES","fmt_SE"],
                        )
```

Now after running the above script I get the following error
```
2024-08-29 10:19:53,993 - distributed.protocol.pickle - ERROR - Failed to serialize <ToPickle: HighLevelGraph with 2 layers.
<dask.highlevelgraph.HighLevelGraph object at 0x1554c1bddfd0>
 0. _read_partition-890b3591-9564-4a79-82e6-39c855e9f7f5
 1. make_meta-36a2af47-2e7a-45c7-8760-bfac82ca87e9
>.
Traceback (most recent call last):
  File "/home/bruno.ariano/conda_envs/tiledb_sql/lib/python3.12/site-packages/distributed/protocol/pickle.py", line 63, in dumps
    result = pickle.dumps(x, **dump_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot pickle 'Config' object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bruno.ariano/conda_envs/tiledb_sql/lib/python3.12/site-packages/distributed/protocol/pickle.py", line 68, in dumps
    pickler.dump(x)
TypeError: cannot pickle 'Config' object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bruno.ariano/conda_envs/tiledb_sql/lib/python3.12/site-packages/distributed/protocol/pickle.py", line 81, in dumps
    result = cloudpickle.dumps(x, **dump_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bruno.ariano/conda_envs/tiledb_sql/lib/python3.12/site-packages/cloudpickle/cloudpickle_fast.py", line 73, in dumps
    cp.dump(obj)
  File "/home/bruno.ariano/conda_envs/tiledb_sql/lib/python3.12/site-packages/cloudpickle/cloudpickle_fast.py", line 632, in dump
    return Pickler.dump(self, obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot pickle 'Config' object
Traceback (most recent call last):
  File "/home/bruno.ariano/conda_envs/tiledb_sql/lib/python3.12/site-packages/distributed/protocol/pickle.py", line 63, in dumps
    result = pickle.dumps(x, **dump_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot pickle 'Config' object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bruno.ariano/conda_envs/tiledb_sql/lib/python3.12/site-packages/distributed/protocol/pickle.py", line 68, in dumps
    pickler.dump(x)
TypeError: cannot pickle 'Config' object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bruno.ariano/conda_envs/tiledb_sql/lib/python3.12/site-packages/distributed/protocol/serialize.py", line 366, in serialize
    header, frames = dumps(x, context=context) if wants_context else dumps(x)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bruno.ariano/conda_envs/tiledb_sql/lib/python3.12/site-packages/distributed/protocol/serialize.py", line 78, in pickle_dumps
    frames[0] = pickle.dumps(
                ^^^^^^^^^^^^^
  File "/home/bruno.ariano/conda_envs/tiledb_sql/lib/python3.12/site-packages/distributed/protocol/pickle.py", line 81, in dumps
    result = cloudpickle.dumps(x, **dump_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bruno.ariano/conda_envs/tiledb_sql/lib/python3.12/site-packages/cloudpickle/cloudpickle_fast.py", line 73, in dumps
    cp.dump(obj)
  File "/home/bruno.ariano/conda_envs/tiledb_sql/lib/python3.12/site-packages/cloudpickle/cloudpickle_fast.py", line 632, in dump
    return Pickler.dump(self, obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot pickle 'Config' object

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bruno.ariano/conda_envs/tiledb_sql/lib/python3.12/site-packages/tiledbvcf/dataset.py", line 993, in map_dask
    return dask_functions.map_dask(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bruno.ariano/conda_envs/tiledb_sql/lib/python3.12/site-packages/tiledbvcf/dask_functions.py", line 111, in map_dask
    return dask.dataframe.from_delayed(partitions)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bruno.ariano/conda_envs/tiledb_sql/lib/python3.12/site-packages/dask/dataframe/io/io.py", line 644, in from_delayed
    meta = delayed(make_meta)(dfs[0]).compute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bruno.ariano/conda_envs/tiledb_sql/lib/python3.12/site-packages/dask/base.py", line 376, in compute
    (result,) = compute(self, traverse=False, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bruno.ariano/conda_envs/tiledb_sql/lib/python3.12/site-packages/dask/base.py", line 662, in compute
    results = schedule(dsk, keys, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bruno.ariano/conda_envs/tiledb_sql/lib/python3.12/site-packages/distributed/protocol/serialize.py", line 392, in serialize
    raise TypeError(msg, str_x) from exc
TypeError: ('Could not serialize object of type HighLevelGraph', '<ToPickle: HighLevelGraph with 2 layers.\n<dask.highlevelgraph.HighLevelGraph object at 0x1554c1bddfd0>\n 0. _read_partition-890b3591-9564-4a79-82e6-39c855e9f7f5\n 1. make_meta-36a2af47-2e7a-45c7-8760-bfac82ca87e9\n>')
```

**Comment by gspowley** [comment]
Hi @bruno-ariano,

These changes will simplify passing in the config values and should avoid the pickling error:

```python
import pathlib
import tiledb
import tiledbvcf
cfg = {}  # <-- use a dict instead of a Config object
cfg["vfs.s3.aws_access_key_id"] = "xxx"
cfg["vfs.s3.aws_secret_access_key"] = "xxx"
cfg["vfs.s3.endpoint_override"] = "xxx"
cfg["vfs.s3.use_virtual_addressing"] = "false"
cfg["vfs.s3.scheme"] = "https"
cfg["vfs.s3.region"] = ""
cfg["vfs.s3.verify_ssl"] = "false"

# read_cfg is not needed
# read_cfg = tiledbvcf.ReadConfig(tiledb_config=cfg)
```

Then pass the `cfg` dict to the `tiledb_config` argument:
```python
ds = tiledbvcf.Dataset(uri, mode = "r", tiledb_config=cfg)
```

For reference - https://tiledb-inc.github.io/TileDB-VCF/documentation/reference/Dataset.html#parameters

**Comment by bruno-ariano** [comment]
Thank you @gspowley that has solved the issue
